services:
  web:
    build: .
    command: gunicorn blog.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=o5TdxxkWG3EoGXR8zFUYVNV5TbTAkE0b9AZytslTzdIN7SQeUFE"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
volumes:
  postgres_data: